### ISSUE TITLE
License of the project

### ISSUE THREAD

**Issue by buremba** [cumulio/cumulio-spotify#2]
Great project! Do you mind attaching the license to the project for those who would like to use cumulio-spotify?

**Comment by TuanaCelik** [comment]
Attached the MIT license 👍 - let us know what you use it for 😊

**Comment by TuanaCelik** [comment]
On that note @buremba there's a separate 'tutorial' repo for this project: https://github.com/cumulio/cumulio-spotify-datatalks 
Each commit is in a way a step we took to build the main cumulio-spotify project, but it might be simpler to start with.

Since creating the project some things in Cumul.io have also changed and we now use Integrations and Web components. cumulio-spotify-datatalks will be migrated to use these too, so it will be more up to date:
[Setting up Integration](https://developer.cumul.io/#set-up-an-integration)
[Generate SSO](https://developer.cumul.io/#integrate-into-your-application)
[Embedding intro](https://developer.cumul.io/#embedding_introduction)

**Comment by buremba** [comment]
Hey @TuanaCelik, thanks for the info! We're actually planning to use the codebase that interacts with Spotify API to build something similar for our open-source project called Metriql. I recently wrote the spec [here](https://github.com/orgs/metriql/teams/sample-projects/discussions/1).

**Comment by TuanaCelik** [comment]
Cool @buremba ! I tried to have a look at the specs you link to but I get a 404. Might be that it's not open to public access yet? I would be interested to see it and what you end up with and I'm sure the rest of the team would be interested as well so let me know :)

**Comment by buremba** [comment]
Hey @TuanaCelik , we moved it to another repo. Here it is: https://github.com/metriql/metriql.com/issues/19
Thanks!
